name: Go

on: [push]

jobs:
  build:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24.x' ]

    steps:
      # https://github.com/actions/setup-go/pkgs/container/checkout
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-go/pkgs/container/setup-go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run go test
        run: go test -json > TestResults-${{ matrix.go-version }}.json
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json