# VOIR: I typo'd the directory name, and github created something different.
# VOIR: - It assumed build (on a module).
# VOIR: - It used downlevel everything.
# VOIR: I merged my edits back into this version.
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

# Temp notes:
# - The matrix part does not appear to be the problem.
# - Indentation / syntax of the upload does appear to be a problem.
# - Renamed the job.
# - Removed the explicit version (that does not appear to be used).
#   This caused a warning - re-inserting the martix reference.


name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23', '1.24.x' ]
    steps:
    # https://github.com/actions/setup-go/pkgs/container/checkout
    - uses: actions/checkout@v4
    # https://github.com/actions/setup-go/pkgs/container/setup-go
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        # cache: false turns off the search for go.sum (that does not exist in
        # a project without dependencies).
        cache: false
        cache-dependency-path: "go.sum"
    - run: go test -v

        
        # https://github.com/actions/upload-artifact
#    - name: Upload test results
#        uses: actions/upload-artifact@v4
#        with:
#          name: Go-results-${{ matrix.go-version }}
#          path: TestResults-${{ matrix.go-version }}.json
 