
name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23', '1.24' ]
    steps:
    # https://github.com/actions/setup-go/pkgs/container/checkout
    - uses: actions/checkout@v4
    # https://github.com/actions/setup-go/pkgs/container/setup-go
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        # cache: false turns off the search for go.sum (that does not exist in
        # a project without dependencies).
        cache: false
    - run: go test -v
